### ISSUE TITLE
[Idea] More friendly Storage interface

### ISSUE THREAD

**Issue by suutaku** [TBD54566975/ssi-service#186]
**Is your feature request related to a problem? Please describe.**
consider use blockchain or something else as a storage, maybe we need a storage register to load storage implementations dynamically. 

**Describe the solution you'd like**
A simplest solution is  make a variable to store all the implementations of storage. when we use it, just get it by `Type`.
What we  should do is just modify some functions in `storage.go` and export a function like `strorage.RegisterStorage(Storage)` to developers. so they can use it register storage at his code as he need and without modify any `ssi-service`'s code.

**Getting it done**
If this idea was OK, I will building this myself, and create a pull request later.

**Comment by decentralgabe** [comment]
thanks @suutaku I agree this is needed to prove out different storage mediums.

please feel free to make the change and submit a PR 😄

**Comment by suutaku** [comment]
#220
