### ISSUE TITLE
[Bug] Using a result parameter before assigning value

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#190]
**Describe the bug**
See title

**To Reproduce**
Pretty sure this is a bug. Suspect line is https://github.com/TBD54566975/ssi-service/blob/9166a2e2e221e8dbde2eb89c43f199df389539e7/internal/did/access.go#L35

**Expected behavior**
I think the line wants to use `maybeKID`

**Supporting Material**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
A test that exercises the function `GetVerificationInformation` should be added first.

**Comment by decentralgabe** [comment]
yes nice find
