### ISSUE TITLE
Speedup tests by caching jsonschemas

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#214]
**Is your feature request related to a problem? Please describe.**
As @suutaku noted in https://github.com/TBD54566975/ssi-service/issues/200#issuecomment-1346169939 the current bottleneck when running unit tests is having to download jsonschema files over the network.

**Describe the solution you'd like**
We should commit to the repository all the used jsonschema files, and have a custom loader that uses them.

**Describe alternatives you've considered**
Keep as is, and suffer slowness.

**Comment by decentralgabe** [comment]
Will be fixed after the uptake of https://github.com/TBD54566975/ssi-sdk/pull/269
