### ISSUE TITLE
[Bug] Integration TestResolveDIDWebIntegration is flaky

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#319]
The flakiness is because `identity.foundation` is using cloudflare to prevent DDOS attacks. When attempting to retrieve the `.well-known file`, then we're getting back an HTML page with a challenge, rather than the json object.

**Comment by michaelneale** [comment]
for testing can we cache a copy - or have an exponential backoff and retry? (cloudflare probably wouldn't liek that either).

**Comment by andresuribe87** [comment]
We can, though it stops being an integration test :)

**Comment by michaelneale** [comment]
well if you can perhaps do it via a proxy then its still testing integration, just not with cloudflare ;)

**Comment by andresuribe87** [comment]
I was going down this path, by creating a simple file server that hosts the file. But I quickly hit a roadblock since `did:web` resolution must use https. That means we need to figure out the whole container<->container secure communication story, and this is easily a can of worms (CAs, certificates, fun!)

Some googling around shows that https://github.com/nginx-proxy/nginx-proxy + ACME is a nice way of setting the whole bit up. It's a big lift so want to hear feedback before actually moving ahead with this.

**Comment by michaelneale** [comment]
@andresuribe87 yeah you are right, that is a heavy lift, maybe too heavy. How upsetting are these flaky tests to you? does a retry fix it? 

Secondly can you point me in the code to where this happens? I wonder if there is some special "well-known" stuff we can do given that its behaviour should be fairly simple.

**Comment by andresuribe87** [comment]
> How upsetting are these flaky tests to you? does a retry fix it?

They trigger my inner engineer 🤣 . Jokes aside, I think having non-flaky integration tests is underrated. It will help us ensure our stuff works correctly and without regressions. Not a big deal right now, but will become a bigger one in the future. I'm happy to simply skip this test for now. I've tried retries and not sure they fix it. Seems like it depends on how cloudflare is feeling and what job executors we get from github. Very moody if you ask me. 

> Secondly can you point me in the code to where this happens?

This is where the `https` is hard coded. 
https://github.com/TBD54566975/ssi-sdk/blob/92be548d54be11b3740b95bb5c568958e5979de0/did/web.go#L114

This is where the get happens.
https://github.com/TBD54566975/ssi-sdk/blob/92be548d54be11b3740b95bb5c568958e5979de0/did/web.go#L182


Some solutions I've seen in the past are to inject a [RoundTripper](https://pkg.go.dev/net/http#RoundTripper) to the `httpClient` instance that's used to fetch the URL content. It's similar to what's done in unit tests using https://github.com/h2non/gock
I would avoid that approach because it requires piping a single httpclient all the way down to the SDK. 

Curious if there's some other ideas! Otherwise I'm simply going to turn this off.

**Comment by michaelneale** [comment]
oh yeah this hurts. 
Can the https be non hard coded and then a very simple local proxy can be shimmed in for CI integration tests?

**Comment by michaelneale** [comment]
@andresuribe87 		urlStr := "https://" + decodedDomain + "/" + DIDWebWellKnownURLPath + DIDWebDIDDocFilename = any reason why it has to have https added ?

**Comment by andresuribe87** [comment]
@michaelneale it's step 3 in the [spec](https://w3c-ccg.github.io/did-method-web/#read-resolve) that it has to be HTTPS :/ 

we can do a special value.... or maybe we can just skip this convo if we do `https://www.tbd.website/.well-known/did.json`. I'll see more to that.

**Comment by michaelneale** [comment]
yeah - we aren't testing cloudflare etc - so if can use a known good one, we should.

**Comment by decentralgabe** [comment]
is this ready to be closed with #321?

**Comment by andresuribe87** [comment]
Fixed by https://github.com/TBD54566975/ssi-service/pull/323
