### ISSUE TITLE
Decouple ServiceKey namespace from KeyStoreAPI namespace

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#367]
We are storing the ServiceKey in the same namespace as the one we use for the `KeyStoreAPI`. What this means is that a caller may override the ServiceKey that was stored, if they pass in `id == "ssi-service-key"` in the [Store Key Request](https://developer.tbd.website/docs/apis/ssi-service#tag/KeyStoreAPI/paths/~1v1~1keys/put)

**Comment by decentralgabe** [comment]
why not just prevent overwriting the key? meaning the id "ssi-service-key" is reserved for the service?

**Comment by andresuribe87** [comment]
> why not just prevent overwriting the key? meaning the id "ssi-service-key" is reserved for the service?

That's certainly one solution.

I think it makes more sense to let users use any id that they want. I also think it's important to separate the ssi-service keys from keys that we're storing on behalf of users. Both have different requirements.

**Comment by decentralgabe** [comment]
I agree @andresuribe87 we should support both paths:
1. bring you own key
2. generate and use a key in the service
