### ISSUE TITLE
Rename presentation definition endpoints

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#375]
Presentation Requests are signed versions of Presentation Definitions, intended for specific audiences.
Today, our API for Presentation Definition returns signed objects when it should not, as Presentation Definitions themselves aren't signed.

**Comment by andresuribe87** [comment]
Can you expand on the rationale behind why Presentation Definition objects
should not be signed?

**Comment by decentralgabe** [comment]
Presentation Definitions, by definition, are unsigned objects. [Presentation Requests](https://identity.foundation/presentation-exchange/#presentation-request) are the signed representation of Presentation Definitions, intended for a specific audience.

I'd first ask "what's the reason to sign a Presentation Definition if it's not a Presentation Request"?

The impetus here is not wanting to see confusing between signed presentation definitions and (signed) presentation requests.

**Comment by andresuribe87** [comment]
I think this might be a simple naming confusion within our API. For instance, the [Create PresentationDefinition](https://developer.tbd.website/docs/apis/ssi-service#tag/PresentationDefinitionAPI/paths/~1v1~1presentation~1definition/put) is in fact creating a `Presentation Request` object.

**Comment by decentralgabe** [comment]
Agree -- a fine resolution of this ticket is just to rename our APIs
