### ISSUE TITLE
[Bug] unknown field "schemaId""

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-service#383]
**Describe the bug**
*A clear and concise description of what the bug is.*

- streamlit application can't produce verifiable credential. 

**To Reproduce**
*Steps to reproduce the behavior:*
1. Go to ssi.benri.io
2. Click on create did. create schema. create VC.
3. See error
```
"error":"invalid create credential request: json: unknown field "schemaId""
```

**Expected behavior**
Credential is issued. 

**Supporting Material**
<img width="812" alt="image" src="https://user-images.githubusercontent.com/8604639/233217338-1fcb20bb-1a00-46e8-a961-35b80296dcda.png">

**Comment by decentralgabe** [comment]
Which version of the SSI Service is being run?

**Comment by andorsk** [comment]
Latest commit: 02e7659790f07e378a60bb0c2fed675b0fd88f32

**Comment by decentralgabe** [comment]
@andorsk can you try updating the service to https://github.com/TBD54566975/ssi-service/commit/d6cf60a2a485a6e6ec2a468d7a3fde72d1f79120 ?

**Comment by andorsk** [comment]
Doing now

**Comment by andorsk** [comment]
@decentralgabe d6 is older than 02. That still ok?

**Comment by decentralgabe** [comment]
https://github.com/TBD54566975/ssi-service/pull/384
