### ISSUE TITLE
[Bug] Unable to build the project, build instructions are likely outdated

### ISSUE THREAD

**Issue by vlad-timofeev** [TBD54566975/ssi-service#398]
**Describe the bug**

I followed the build instructions from `README.md` file, but was not able to execute `mage build` command successfully.

```
[user@tbd] ➜  ~/tbd/ssi-service git:(main) mage build                                                                                                                                      INSERT
Building project...
# github.com/TBD54566975/ssi-sdk/oidc/issuance
../../go/pkg/mod/github.com/!t!b!d54566975/ssi-sdk@v0.0.3-alpha.0.20230420000447-6d87cd195314/oidc/issuance/metadata.go:17:37: undefined: strings.CutPrefix
Error: running "go build -tags jwx_es256k ./..." failed with exit code 2
```

**To Reproduce**

Follow the [build instructions](https://github.com/TBD54566975/ssi-service#build--test)

**Expected behavior**

Successful compilation.

**Supporting Material**

None

**Environment (please complete the following information):**
 - OS: Linux Fedora 37
 - Go: 1.19.8

**Additional context**

I think that the problem happens because [CutPrefix function was introduced in Go version 1.20](https://golang.google.cn/pkg/strings/#CutPrefix), whereas I have 1.19.8 installed, which is the latest version I can get for my OS with `sudo dnf -y install go` command.

Does `ssi-service` require Go 1.20, which is only 3 months old? If yes, then [Developer prerequisites](https://github.com/TBD54566975/ssi-service/blob/main/CONTRIBUTING.md#development-prerequisites) are out of date, because they indicate Go 1.17 as a requirement.  The [README](https://github.com/TBD54566975/ssi-service/blob/main/README.md?plain=1#L2) shows Go version 1.19.4.

**Comment by decentralgabe** [comment]
Yes 1.20 is required. I'll update the docs. Thanks for flagging.

**Comment by vlad-timofeev** [comment]
Thank you for confirming that 1.20 is the required Go version. After installing it, I no longer encounter the error.
