### ISSUE TITLE
Keystore Service

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#40]
The SSI Service will need to manage keys for DIDs amongst other things.
Keys should be stored in a key-store that exposed sign/verify, encrypt/decrypt primitives. Eventually a permissioning model can be layered on top of the key service.

The key service will need to be used by any sub-service that depends on signing or verification, such as during credential issuance, or presentation exchange flows.

The keystore should encrypt keys with a service-level key that can be provided via configuration.

**Comment by rishabhmalhotra** [comment]
Are the devs considering building out a keystore providing given primitive's or are they open to exploring exploring existing options/building interfaces to add primitives to existing options?

**Comment by decentralgabe** [comment]
@rishabhmalhotra open to both. was going to provide an interface with a single implementation, though presumably it can be an external API too. open to contributions here.

**Comment by rishabhmalhotra** [comment]
Thanks for clarifying!

**Comment by decentralgabe** [comment]
@rishabhmalhotra I am closing this with my implementation in #62. Please open a new issue for external keystore support if you desire it.
