### ISSUE TITLE
Credential Manifest: support specifying credential data on issuance

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#415]
[Currently we do not add data to a credential](https://github.com/TBD54566975/ssi-service/blob/main/pkg/service/manifest/response.go#L88) upon issuance with Credential Manifest. 

This task is to add credential data based on a Credential Application and Issuance Template.

**Comment by andresuribe87** [comment]
Issuance Templates support adding data to a credential from the `data` field. All values in the object will be used to populate credential claims as seen below https://github.com/TBD54566975/ssi-service/blob/faa7a9ad62798d1b32692548c0bd109460ae8b94/pkg/service/manifest/response.go#L160-L171

Is this the feature that you're describing? If not, mind providing an example?

**Comment by decentralgabe** [comment]
whoops, missed that. is it supported without a template, as a part of an operation API?

meaning
1. set up cred manifest
2. get an application
3. need to submit an operation with the data to populate the cred

**Comment by decentralgabe** [comment]
If not can repurpose the issue for the todo ```// TODO(gabe) need to add in data here to match the request + schema```

**Comment by andresuribe87** [comment]
Operation is a promise. Users cannot do anything with an operation except wait for it to be finished.

From what I understand, the [Review Application](https://developer.tbd.website/docs/apis/ssi-service#tag/ApplicationAPI/paths/~1v1~1manifests~1applications~1%7Bid%7D~1review/put) endpoint achieves what you are describing with the `credential_overrides` field.

**Comment by decentralgabe** [comment]
Closing then, my mistake
