### ISSUE TITLE
Webhooks: only run middleware if a webhook is registered for a given endpoint

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#435]
Currently the webhook middleware tries to run `PublishWebhook` on each webhook-enabled endpoint, regardless of whether a webhook is registered or not. We can reduce the noisiness here by detecting whether there are any webhooks registered for a particular endpoint.

**Comment by andresuribe87** [comment]
Checking for registration is done inside `PublishWebhook` in https://github.com/TBD54566975/ssi-service/blob/7047be55d3d57ca5e4ee4919126e4acdeb275444/pkg/service/webhook/service.go#L182-L191

Are you proposing to move that into the middleware?

**Comment by decentralgabe** [comment]
yes

**Comment by andresuribe87** [comment]
What are the advantages of putting that check in the middleware?

I'm not concerned that much about the location (I can see arguments for it belonding inside the `PublishWebhook` function, or inside the middleware). My concern is that it's done inside a separate go-routine. Otherwise, the critical path to return a response would be blocked on checking the webhook registry. Doing that check in the same goroutine where the handler is run impacts latency across all endpoints.

**Comment by decentralgabe** [comment]
if you look at the logs you'll see the noise the middleware is creating (not concerned about the log itself but what it signifies). a few calls of overhead for each request. when there aren't any webhooks registered these calls are superfluous, so if we could detect that and limit them we'll save some cycles.

**Comment by andresuribe87** [comment]
Sorry I don't follow. Would you mind drafting some pseudo-code of what you're thinking?

**Comment by nitro-neal** [comment]
```
	credentialAPI.PUT("", middleware.Webhook(webhookService, webhook.Credential, webhook.Create), credRouter.CreateCredential)
	
	...
	
	go webhookService.PublishWebhook(c, noun, verb, buf)
	
	...
	
	nounString := string(noun)
	verbString := string(verb)
	webhook, err := s.storage.GetWebhook(timeoutCtx, nounString, verbString)
	if err != nil {
		logrus.WithError(err).Debugf("getting webhook: %s:%s", nounString, verbString)
		return
	}

```

I think what Gabe is saying is that every call to create credential -even if no webhook was registered for that event- goes through a go routine, where it then does a lookup and sees that one doesn't exist.

Two things I can think of to solve this:

1. before the go routine can do a db read to see if webhook exists, and if it does not don't even go in the go routine.
2. ?Build a distributed cache? Currently are we supporting that SSI-Service will be a horizontally distributed system? if so we can't do a simple in memory cache as it wouldn't be reflected across all boxes

**Comment by decentralgabe** [comment]
it is noisy and unnecessary but to your point @andresuribe87 it's not a meaningful cost given the functionality it provides, as such, closing.
