### ISSUE TITLE
[Server] switch all usages of context to gin.Context

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#441]
Since we're using gin, we should use it's context everywhere.

**Comment by andresuribe87** [comment]
I don't think we should be using the gin.Context everywhere, only where it's mandatory. 

Functions and methods should be liberal in what they accept, and concrete in what they return. This makes more robust code. In short "Accept interfaces, return structs".

**Comment by decentralgabe** [comment]
Agreed. Keep it at the server level where it is now.
