### ISSUE TITLE
Consistency between APIs that return many objects

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#449]
Some API endpoints use `List`([List Operations](https://developer.tbd.website/docs/apis/ssi-service/#tag/OperationAPI/paths/~1v1~1operations/get)) while others use `Get` ([Get DIDs](https://developer.tbd.website/docs/apis/ssi-service/#tag/DecentralizedIdentityAPI/paths/~1v1~1dids~1%7Bmethod%7D/get))

We should make it consistent. 

Personal preference is to use List as described [here](https://cloud.google.com/apis/design/standard_methods#list).

**Comment by decentralgabe** [comment]
fixed in #470
