### ISSUE TITLE
Support key revocation

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#451]
Key revocation is partially implemented. You can revoke keys, but this does not have any functional impact to the key's usage.

We should update the behavior to enforce not being able to use revoked keys.

https://github.com/TBD54566975/ssi-service/blob/main/pkg/service/keystore/service.go#L127

**Comment by vlad-timofeev** [comment]
#546 and #579 are now merged, is this issue good to be closed?

**Comment by decentralgabe** [comment]
yes!
