### ISSUE TITLE
[Bug] memory crash

### ISSUE THREAD

**Issue by jdutchak** [TBD54566975/ssi-service#452]
mage run or docker-compose up --build

mac 13.3.1  M2 chip

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x39 pc=0x100ce5690]

goroutine 87 [running]:
github.com/docker/buildx/builder.(*Builder).Validate(0x101ee58a0?)
        github.com/docker/buildx@v0.10.4/builder/builder.go:111 +0x20
github.com/docker/buildx/builder.New({0x101ee58a0?, 0x14000170500}, {0x0, 0x0, 0x140003d0ab0?})
        github.com/docker/buildx@v0.10.4/builder/builder.go:101 +0x290
github.com/docker/compose/v2/pkg/compose.(*composeService).doBuildBuildkit(0x140002ec840, {0x101ed4d80, 0x14000660190}, 0x0?, {0x1016872b3, 0x4})
        github.com/docker/compose/v2/pkg/compose/build_buildkit.go:36 +0x68
github.com/docker/compose/v2/pkg/compose.(*composeService).build.func1({0x101ed4d80, 0x14000660190}, {0x14000427390, 0x3})
        github.com/docker/compose/v2/pkg/compose/build.go:112 +0x5b4
github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
        github.com/docker/compose/v2/pkg/compose/dependencies.go:127 +0x5c

**Comment by decentralgabe** [comment]
I believe this may be specific to the M2 chip, since I've run the same command on my M1 with no issue.

Are you using Docker Desktop? https://tutorials.tinkink.net/en/mac/how-to-use-docker-on-m1-mac.html

**Comment by jdutchak** [comment]
yes docker desktop

**Comment by jdutchak** [comment]
also whats the recommended server to use? AWS 
Amazon 2
Ubuntu 
?

**Comment by jdutchak** [comment]
gui docker no longer exists either in compose yaml

  gui:
    build:
      context: ../
      dockerfile: build/Dockerfile-gui

**Comment by decentralgabe** [comment]
@jdutchak you might need to try `docker-compose stop &&docker-compose up --build --remove-orphans` again since the error seems related to docker-compose itself

the GUI is being removed here - https://github.com/TBD54566975/ssi-service/pull/450

as for where to run - we're planning on supporting all major clouds. have tested on AWS internally

**Comment by jdutchak** [comment]
are the swagger docs being removed too?

**Comment by decentralgabe** [comment]
more accurately I should say the streamlit gui is deprecated in favor of https://github.com/TBD54566975/ssi-admin-ui

we have yet to integrate that into our docker-compose here https://github.com/TBD54566975/ssi-service/issues/454

swagger was moved to be served from the service itself, so need for a special binary. docs could be better perhaps. you can view it as of https://github.com/TBD54566975/ssi-service/commit/817610d1ff91ea1061b7328c752df273a91e757e by sending a request to `/swagger`
