### ISSUE TITLE
[Bug] Update Credential Status result not reflected in Credential Status in subsequent calls

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/ssi-service#473]
**Describe the bug**
When issuing a credential where `suspendable == true` and after calling `UpdateCredentialStatus` with `suspended: true`, the credential should return with `suspended == true`. It seems `suspended: true` is being stored in the redis store for the credential, but the credential returned by the service still shows as `suspended == false`.

**To Reproduce**
*Steps to reproduce the behavior:*
1. Go through the steps to issue a credential, and set `suspendable` to true in the payload.
2. Call `UpdateCredentialStatus` with `suspended: true` in the body. The response will show `suspended: true` as expected.
3. Get the credential's status by credential ID to observe that the response shows `suspended: false`, which is not expected.
4. List all credentials and scroll to the credential you just created to observe that the property shows as `Suspended: false`, which is not expected.
5. Navigate to Redis Commander at `http://localhost:9001/` and find the credential in the file tree. You should see that `suspended == false`. 

**Expected behavior**
The credential should return with `suspended == true`.

**Supporting Material**
<img width="500" alt="Screenshot 2023-05-24 at 1 44 00 AM" src="https://github.com/TBD54566975/ssi-service/assets/102400653/4c13c5e3-5fa4-4cdf-a89d-2cedfb6609fc">
<img width="500" alt="Screenshot 2023-05-24 at 1 44 10 AM" src="https://github.com/TBD54566975/ssi-service/assets/102400653/8a98d19e-df5a-4636-a263-2865818f528e">
<img width="500" alt="Screenshot 2023-05-24 at 1 45 27 AM" src="https://github.com/TBD54566975/ssi-service/assets/102400653/293f8195-17dd-4f63-9e89-8a126e04407f">
<img width="500" alt="Screenshot 2023-05-24 at 1 49 08 AM" src="https://github.com/TBD54566975/ssi-service/assets/102400653/f591c86d-9c4b-4ecc-9527-23f0fc922f7f">

**Environment (please complete the following information):**
 - OS: MacOS
 - Version 13.3.1

**Comment by nitro-neal** [comment]
pr for this - https://github.com/TBD54566975/ssi-service/pull/487
