### ISSUE TITLE
[Bug] /swagger ?

### ISSUE THREAD

**Issue by jdutchak** [TBD54566975/ssi-service#485]
is the plan to serve the swagger yaml or a the swagger editor here because /swagger doesn't load  
but /swagger.yaml does 

works - http://localhost:8080/swagger.yaml 
does not -- http://localhost:8080/swagger

**Comment by jdutchak** [comment]
gotcha, PR to update README

## HTTP Endpoints
You can find all HTTP endpoints by checking out the swagger docs at: `http://localhost:8080/swagger`
to
## HTTP Endpoints
You can find all HTTP endpoints by checking out the swagger docs at: `http://localhost:8080/swagger/index.html`

**Comment by decentralgabe** [comment]
https://github.com/TBD54566975/ssi-service/pull/486
