### ISSUE TITLE
[Idea] Make query filter optional when returning credentials 

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/ssi-service#488]
**Is your feature request related to a problem? Please describe.**
When requesting credentials, a query param of `issuer`, `subject` or `schema` is required and the response is filtered accordingly. 

**Describe the solution you'd like**
Would be great to make this query param optional, and return all credentials in the absence of a filter.

**Describe alternatives you've considered**
Currently traversing all issuer DIDs stored in the db and requesting credentials by issuer in order to get all credentials stored in the db

**Comment by decentralgabe** [comment]
fix is in https://github.com/TBD54566975/ssi-service/pull/489

**Comment by nitro-neal** [comment]
https://github.com/TBD54566975/ssi-service/pull/489 is merged in
