### ISSUE TITLE
Update credential creation so the ID is a URL

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#500]
The [spec](https://www.w3.org/TR/vc-data-model-2.0/#identifiers) recommends that IDs can be dereferenced. This is currently not supported by ssi-service. 

We should:
* Set a config parameter for the base URL for the service (not sure if it exists already).
* When creating credentials, call the `SetID(id)` method with `id = baseURL + "/v1/credentials/" + uuid.NewString()`. This will allow the ID to be dereferenced.

**Comment by decentralgabe** [comment]
the config exists, and this is what is going on for schemas already as per #494. we should be careful the config still works after #502
