### ISSUE TITLE
[Bug] ID includes `localhost`

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/ssi-service#544]
**Describe the bug**
When using the Credential API, the service returns the `id` field with `http://localhost`

**To Reproduce**
1. Create a credential with the service.
2. Observe the `id` field in the response. It should start with `localhost`
3. Call GET to get credentials from the service.
4. Observe the `id` field in the response. It should start with `localhost`

**Expected behavior**
The `id` field should only return the credential ID

**Supporting Material**
<img width="970" alt="Screenshot 2023-06-15 at 3 22 18 AM" src="https://github.com/TBD54566975/ssi-service/assets/102400653/61a8fb4b-057c-454b-9d87-e71c05bedbf8">

**Comment by andresuribe87** [comment]
Reopening this to make a distinction between the `id` field at the top level of the response, and the `credential.id` field. The former should be a UUID while the latter should be dereference-able.
