### ISSUE TITLE
Add support for evidence in VCs

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#550]
Evidence should be added as an optional field https://github.com/TBD54566975/ssi-service/blob/main/pkg/server/router/credential.go#L99

It is supported in the SDK https://github.com/TBD54566975/ssi-sdk/blob/main/credential/model.go#L29

Since it is an any, we may want to pre-populate some fields like `id` and `type` and leave the rest as free form.

This is a prerequsite to uptake in the UI; cc: @kirahsapong

**Comment by nitro-neal** [comment]
pr - https://github.com/TBD54566975/ssi-service/pull/553
