### ISSUE TITLE
DID Web creation override

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/ssi-service#554]
**Describe the bug**
When you create 2 did webs with the same id, it 'deletes' the old one

**To Reproduce**
<img width="791" alt="image" src="https://github.com/TBD54566975/ssi-service/assets/5314059/fb6c7128-7df9-4632-9875-f616074b46a9">

<img width="814" alt="image" src="https://github.com/TBD54566975/ssi-service/assets/5314059/ea2618f7-2d4e-4337-88a3-97b03bffe9ce">

<img width="775" alt="image" src="https://github.com/TBD54566975/ssi-service/assets/5314059/cd31650b-d267-4021-a6aa-67484e2c82b4">

<img width="790" alt="image" src="https://github.com/TBD54566975/ssi-service/assets/5314059/5b5ec176-e65a-4873-91c8-e9e73fa2e1c7">

Notice the X is different and the old did web is 'gone?' 

Is this by design ?

**Comment by nitro-neal** [comment]
For this how about we can't make another did - web with the same id?
that should fix the issue

**Comment by decentralgabe** [comment]
this is a bug we should fail if we try to overwrite, also `didWebID` should be changed to `didWebId`
