### ISSUE TITLE
Support signing blobs with an ION DID that was created by SSI-service

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#555]
Per https://discord.com/channels/937858703112155166/1118914862106542100/1121125803342692483, there is a need to support signing with an  so we can cleanly attach to DWNs.

The alternatives include:

### Option 1. 

- Create a `v1/keys/sign` endpoint.
- This effectively is becoming more like a KMS. Not ideal.

### Option 2.  <-- my recommendation

- Expose the patch add-public-keys (as described in https://identity.foundation/sidetree/spec/#add-services) in order to update an ION DIDs. v1/dids/ion would be extended.
- Good to have management of DIDs within ssi-service.

### Option 3.

- Allow adding a custom `alsoKnownAs` to ION DIDs.
- Unknown if this is supported by ION. It's unspecified in sidetree. Probably not.

### Option 4

- Allow setting `controller` to an ION DID upon creation.
- Sidetree does not supports having a separate controller from the creator according to https://github.com/decentralized-identity/ion/issues/268

**Comment by andresuribe87** [comment]
@mistermoe would option 2 work?

**Comment by andresuribe87** [comment]
There's another alternative that I failed to mention

### Option 5
* Implement  https://github.com/TBD54566975/ssi-service/tree/main/sip/sips/sip9, where the private keys are stored external to ssi-service. 
* This means that all signing operations (e.g. creating a presentation request) would become async.
* This would take longer to implement.

**Comment by mistermoe** [comment]
agree that option 1 is not ideal. opens a large can of worms imo for two reasons:
* there are many signature formats. General Jws? Compact Jws? Jwt? dweb messages use General Jws
* motivation behind a generalized `sign` endpoint would also end up necessitating a generalized `encrypt` endpoint. to your point, very much so seems like SSI service would basically become a KMS

**Comment by mistermoe** [comment]
> Per https://discord.com/channels/937858703112155166/1118914862106542100/1121125803342692483, there is a need to support signing with an so we can cleanly attach to DWNs.

what we're after is the ability to use a single DID for a PFI. PFIs need to sign dweb messages (and potentially other things) and they also need to sign presentation requests.  we're using the SSI service to create presentation requests and verify presentation submissions.

in order to achieve what we're aiming for, we need to be able to sign messages using the same DID in both the PFI service and the SSI service. this can be achieved in many ways. 

_Generally speaking_, the ask is: support for using the same ION DID to sign what the SSI service produces _and_ whatever else the controller of that DID wants to sign that isn't specific to SSI service (e.g. dweb messages).

**Comment by decentralgabe** [comment]
I would recommend going with the "add other keys" approach, meaning....

1. An ION DID is created and managed by the SSI Service
2. Another key is generated in another service/client (entity)
3. That entity submits to the SSI Service that they'd like to add a new key to the ION DID
4. The SSI Service updates the ION DID doc and anchors that update
5. The other entity is now able to act as the DID

**Comment by andresuribe87** [comment]
Closing as a duplicate of #340 

Will track there.

**Comment by jiyoontbd** [comment]
@andresuribe87 so are we going with option 2, which is being tracked in issue #340?

and, would completion of #340 allow me to fulfill this requirement:
> as a PFI, i want to sign dweb messages with the private key associated with my DID

and if it does, can you briefly explain how that would work? would i have to ping SSI service every time i want to sign dweb messages (seems like no, but want to double check)

**Comment by andresuribe87** [comment]
> so are we going with option 2, which is being tracked in issue https://github.com/TBD54566975/ssi-service/issues/340?

Yes. 

> would completion of https://github.com/TBD54566975/ssi-service/issues/340 allow me to fulfill this requirement:

Yes it would

> and if it does, can you briefly explain how that would work? 

Of course! Here's the flow
1. You create a DID ION by calling `v1/dids/ion`. Let `did:ion:123` be the one you created. 
2. You generate a cyrpto key pair `(secret, public)` on the client side. 
3. You call `v1/dids/ion/did:ion:123` and pass a payload that includes the `public` key generated. This will tell ssi-service to update the diddoc referenced by `did:ion:123` so that the public key passed in can be used to verify that payloads belong to `did:ion:123`.
4. You can use the `secret` key to sign dweb messages.

Let me know if that makes sense @jiyoontbd

**Comment by jiyoontbd** [comment]
i think this flow makes sense. thanks @andresuribe87 !!
