### ISSUE TITLE
[Bug] Tutorial has old api

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/ssi-service#605]
**Describe the bug**
https://developer.tbd.website/blog/issue-verifiable-credential-manually/ is linked from readme, but mentions `issuerKid` which is no longer valid. 

**To Reproduce**
Try the tutorial 

I think we can have a more end to end flow in the readme as well as the tutorial (I will look at this as well).

**Comment by michaelneale** [comment]
the issuerKid property in the CURL examples is now verificationMethodId

**Comment by decentralgabe** [comment]
We've discussed this in the past, the tutorials **need to** point to a specific version of the service or this will keep happening. I'll update the tutorial and point it to the latest commit hash in https://github.com/TBD54566975/developer.tbd.website

**Comment by michaelneale** [comment]
@decentralgabe tutorials yes, but ideally not a blog (which is a point in time post, and will naturally get stale).

**Comment by decentralgabe** [comment]
We've removed references to this post in the service.
