### ISSUE TITLE
Publish OpenAPI Doc to GitHub Pages

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#61]
1. Create a gh-pages branch
2. Create an action on merge to main to run `mage spec` and generate the latest OpenAPI docs
3. Move files to the correct place, to surface the docs on gh pages

**Comment by decentralgabe** [comment]
Also need to make the documentation much clearer!

**Comment by andresuribe87** [comment]
Closing this given that we're publishing things automatically to https://developer.tbd.website/docs/apis/ssi-service/

This was addressed in #282 and #275 and #249 and #253
