### ISSUE TITLE
The pageSize and pageToken parameters are perhaps not working when calling the ListSubmissions function.

### ISSUE THREAD

**Issue by pengpeng** [TBD54566975/ssi-service#626]
I found that when calling

http://localhost:3000/v1/presentations/submissions?pageSize=1&filter=status="approved"
the filter parameter is effective, but the pageSize parameter is not.

Furthermore, I found that

`pageSizeStr := framework.GetParam(c, *PageSizeParam*)`

and

`queryPageToken := framework.GetParam(c, *PageTokenParam*)`

in the `ParsePaginationParams` function both return nil.

I modified them to

`pageSizeStr := framework.GetQueryValue(c, *PageSizeParam*)`

and

`queryPageToken := framework.GetQueryValue(c, *PageTokenParam*)`

and it seems to work correctly in terms of the number of results returned. Considering that both functions `ListDIDsByMethod` and `ListSubmissions` that call `ParsePaginationParams` are GET methods, would `GetQueryValue` be a better choice?

**Comment by andresuribe87** [comment]
Thanks for flagging @pengpeng

> Considering that both functions ListDIDsByMethod and ListSubmissions that call ParsePaginationParams are GET methods, would GetQueryValue be a better choice?

You are absolutely correct. PR incoming soon.
