### ISSUE TITLE
[Bug] DID configuration resolution not working

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/ssi-service#682]
We need to test this vs well known did configurations

curl -X PUT 'localhost:3000/v1/did-configurations/verification' -d '{
  "origin": "https://www.hoekstraonline.net/"
}'

Seems to have issues and getting an error 
"verifying JWT credential: error getting key to verify credential<>: getting raw jwk: failed to build public key: invalid curve algorithm secp256k1"

**Comment by mahoekst** [comment]
Decoded token from did-configuration.json

{
  "alg": "ES256K",
  "kid": "did:web:www.hoekstraonline.net#98cc553d8e7b4558848edfabe63b2bdbvcSigningKey-687f3"
}.{
  "sub": "did:web:www.hoekstraonline.net",
  "iss": "did:web:www.hoekstraonline.net",
  "nbf": 1678754549,
  "exp": 2467759349,
  "vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://identity.foundation/.well-known/contexts/did-configuration-v0.0.jsonld"
    ],
    "issuer": "did:web:www.hoekstraonline.net",
    "issuanceDate": "2023-03-14T00:42:29.640Z",
    "expirationDate": "2048-03-14T00:42:29.640Z",
    "type": [
      "VerifiableCredential",
      "DomainLinkageCredential"
    ],
    "credentialSubject": {
      "id": "did:web:www.hoekstraonline.net",
      "origin": "https://www.hoekstraonline.net/"
    }
  }
}.[Signature]

**Comment by mahoekst** [comment]
And the resolved did:web:www.hoekstraonline.net

{
  "@context": "https://w3id.org/did-resolution/v1",
  "didDocument": {
    "id": "did:web:www.hoekstraonline.net",
    "@context": [
      "https://www.w3.org/ns/did/v1",
      {
        "@base": "did:web:www.hoekstraonline.net"
      }
    ],
    "service": [
      {
        "id": "#linkeddomains",
        "type": "LinkedDomains",
        "serviceEndpoint": {
          "origins": [
            "https://www.hoekstraonline.net/"
          ]
        }
      },
      {
        "id": "#hub",
        "type": "IdentityHub",
        "serviceEndpoint": {
          "instances": [
            "https://beta.hub.msidentity.com/v1.0/a7dc3bd1-d30c-4a6c-bd82-fbdde3e191c0"
          ]
        }
      }
    ],
    "verificationMethod": [
      {
        "id": "#98cc553d8e7b4558848edfabe63b2bdbvcSigningKey-687f3",
        "controller": "did:web:www.hoekstraonline.net",
        "type": "EcdsaSecp256k1VerificationKey2019",
        "publicKeyJwk": {
          "crv": "secp256k1",
          "kty": "EC",
          "x": "s7RkRa9xsDbYfBquIqz0mD5qhNoeaZRAHNLRzxVl2nQ",
          "y": "sHk42K4ygvq9iXLSolHresG9rZpRvLPV308gZ9DeHy8"
        }
      }
    ],
    "authentication": [
      "#98cc553d8e7b4558848edfabe63b2bdbvcSigningKey-687f3"
    ],
    "assertionMethod": [
      "#98cc553d8e7b4558848edfabe63b2bdbvcSigningKey-687f3"
    ]
  },
  "didResolutionMetadata": {
    "contentType": "application/did+ld+json",
    "pattern": "^did:(?web:|jwk:|key:).+$"
  },
  "didDocumentMetadata": {}
}

**Comment by mahoekst** [comment]
I guess it doesn't like this key to validate the signature
"verificationMethod": [
{
"id": "#98cc553d8e7b4558848edfabe63b2bdbvcSigningKey-687f3",
"controller": "did:web:www.hoekstraonline.net",
"type": "EcdsaSecp256k1VerificationKey2019",
"publicKeyJwk": {
"crv": "secp256k1",
"kty": "EC",
"x": "s7RkRa9xsDbYfBquIqz0mD5qhNoeaZRAHNLRzxVl2nQ",
"y": "sHk42K4ygvq9iXLSolHresG9rZpRvLPV308gZ9DeHy8"
}

**Comment by mahoekst** [comment]
Adding the build tag to the launch.json fixed the issue. 

"configurations": [
        {
            "name": "Launch SSI Service local",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "cmd/ssiservice/main.go",
            "env": {
                "ENV": "local"
            },
            "envFile": "${workspaceFolder}/config/.env",
            **"buildFlags": "-tags=jwx_es256k"**
        }
    ]
