### ISSUE TITLE
Document build dependencies for Linux

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/ssi-service#78]
Document installation of `go` and `mage` for Linux.

**Comment by decentralgabe** [comment]
Pointing to the corresponding Mage and go documentation should be sufficient.

**Comment by ALRubinger** [comment]
+1 - linked PR does this.

**Comment by decentralgabe** [comment]
Fixed https://github.com/TBD54566975/ssi-service/commit/e0e2f33d36fc21b2ecf3746eda3638f8b3281664
