### ISSUE TITLE
Validation framework to make sure an application adheres to the requirements of a manifest

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/ssi-service#95]
Create a library that can generically validate many aspects of SSI as it stands in SSI-Service. 

Currently there is a simple validation function: https://github.com/TBD54566975/ssi-service/pull/94 . I want to expand upon this and create a new isValid function that is more robust and can handle different ssi objects

**Comment by decentralgabe** [comment]
This should be moved to the ssi-sdk, to encapsulate the validity of cred manifest objects in a generic manner

**Comment by nitro-neal** [comment]
went in here: https://github.com/TBD54566975/ssi-service/pull/128/files
